var GAME_LEVELS = [
  ["  x                            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                             ##                           x  ",
   "  x                                           yyyyyy                         x  ",
   "  x                                                        yyy               x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                  o                                                       x  ",
   "  x                                     yyyyy                                x  ",
   "  x                                              x        x          o o o   x  ",
   "  x                                              x!!!!!!!!x                  x  ",
   "  x                                              xxxxxxxxxx                  x  ",
   "  x                                                                 yyyyyyy  x  ",
   "  x                yyyyy        yyyyy                                        x  ",
   "  x                                                                          x  ",
   "  x     z                                                      yy      z     x  ",
   "  x                                     yyyy                                 x  ",
   "  x  @               ####                                                    x  ",
   "  xxxxxxxxxx     xxxxxxxxxxxxxx                 #########        xxxxxxxxxxxxx  ",
   "           x     x            x               yyyyyyyyyyyyy      x              ",
   "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
   "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
   "           xxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                                                                                ",
   "                                                                                "],
   ["  x                            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                             ##                           x  ",
    "  x                                           yyyyyy                         x  ",
    "  x                                                        yyy               x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                  o                                                       x  ",
    "  x                                     yyyyy                                x  ",
    "  x                                              x        x          o o o   x  ",
    "  x                                              x!!!!!!!!x                  x  ",
    "  x                                              xxxxxxxxxx                  x  ",
    "  x                                                                          x  ",
    "  x        yyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                     x  ",
    "  x                                                                          x  ",
    "  x                    z                                      yyyyyyyyyyyy   x  ",
    "  x                                     yyyy                                 x  ",
    "  x  @               ####                                                    x  ",
    "  xxxxxxxxxx     xxxxxxxxxxxxxx                 #########        xxxxxxxxxxxxx  ",
    "           x     x            x               yyyyyyyyyyyyy      x              ",
    "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
    "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
    "           xxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
    "                                                                                ",
    "                                                                                "],
    ["  x                            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
     "  x                                                                          x  ",
     "  x                                                                          x  ",
     "  x                                                                          x  ",
     "  x                                                                          x  ",
     "  x                                                                          x  ",
     "  x                                             ##                           x  ",
     "  x                                           yyyyyy                         x  ",
     "  x                                                        yyy               x  ",
     "  x                                                                          x  ",
     "  x                                                                          x  ",
     "  x                  o                                                       x  ",
     "  x                                     yyyyy                                x  ",
     "  x                                              x        x          o o o   x  ",
     "  x                                              x!!!!!!!!x                  x  ",
     "  x                                              xxxxxxxxxx                  x  ",
     "  x                                                                          x  ",
     "  x        yyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                     x  ",
     "  x                                                                          x  ",
     "  x                    z                                      yyyyyyyyyyyy   x  ",
     "  x                                     yyyy                                 x  ",
     "  x  @               ####                                                    x  ",
     "  xxxxxxxxxx     xxxxxxxxxxxxxx                 #########        xxxxxxxxxxxxx  ",
     "           x     x            x               yyyyyyyyyyyyy      x              ",
     "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
     "           x!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x              ",
     "           xxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
     "                                                                                ",
     "                                                                                "],
     ["  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x                                                      x  ",
      "  x      x   x   x    x   x    x   x  x  x   x  x        x  ",
      "  x       xox   x x   x   x    x   x  x  xxoox  x        x  ",
      "  x        x   x   x  x   x    x o x  x  x x x  x        x  ",
      "  x        x    x x   xooox    xoxox  x  x  xx  o        x  ",
      "  x        x     x    xxxxx     x x   x  x   x  x        x  ",
      "  x                                                      x  ",
      "  x  @                                                   x  ",
      "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
      "                                                            "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
